CI: Update NetBSD
For variety, use CMake and Ninja.

diff --git a/.github/workflows/netbsd.yml b/.github/workflows/netbsd.yml
--- a/.github/workflows/netbsd.yml
+++ b/.github/workflows/netbsd.yml
@@ -9,24 +9,31 @@ on:
     branches: [ master ]
   workflow_dispatch:
 
+permissions: {}
+
 jobs:
-  NetBSD-test:
+  NetBSD:
     runs-on: ubuntu-latest
-    name: Test xz on NetBSD
+    name: NetBSD
     steps:
-    - uses: actions/checkout@v4.1.6
-    - name: Test in NetBSD
-      id: test
-      uses: vmactions/NetBSD-vm@dd0161ecbb6386e562fd098acf367633501487a4 #v1.1.3
-      with:
-        usesh: true
-        prepare: |
-          /usr/sbin/pkg_add -v autoconf automake gmake gettext-tools gtar-base libtool-base m4 po4a
-        run: |
-          set -e
-          export LC_ALL=C LANG=C
-          uname -a
-          ./autogen.sh
-          ./configure --enable-werror
-          make
-          make check VERBOSE=1
+      - uses: actions/checkout@v4
+
+      - name: Test in NetBSD
+        id: test
+        uses: vmactions/netbsd-vm@46a58bbf03682b4cb24142b97fa315ae52bed573 #v1.1.8
+        with:
+          usesh: true
+          prepare: >
+            /usr/sbin/pkg_add -v
+            cmake
+            gettext-tools
+            ninja-build
+            po4a
+          run: |
+            set -e
+            uname -a
+            ./po4a/update-po
+            # Innocent putc() triggers strict-overflow warnings.
+            cmake -G Ninja -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS='-g -O2 -pipe -Wno-error=strict-overflow' -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
+            ninja -C build
+            ctest --test-dir build --output-on-failure
